site_name: Firefly III MCP Server
site_description: Model Context Protocol server for Firefly III personal finance management
site_author: Firefly MCP Team
site_url: https://yourusername.github.io/firefly-mcp/

repo_name: yourusername/firefly-mcp
repo_url: https://github.com/yourusername/firefly-mcp
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.action.edit

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation.md
    - Configuration: configuration.md
    - Quick Start: quickstart.md
  - MCP Integration: integrations.md
  - API Reference:
    - Available Operations: api/operations.md
    - Account Management: api/accounts.md
    - Transactions: api/transactions.md
    - Budgets: api/budgets.md
    - Categories & Tags: api/categories-tags.md
    - Bills & Rules: api/bills-rules.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - MCP Inspector: development/mcp-inspector.md
  - Troubleshooting: troubleshooting.md
  - License: license.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/firefly-mcp
  version:
    provider: mike
